SELECT
    f.UNITCODE,
    f.BRANCHID,
    b.DESCRIPTION AS BRANCH_NAME,
    b.CITY,
    f.UNITTYPE,
    ut.DESCRIPTION AS UNIT_TYPE_DESC,
    f.UNITCLASS,
    uc.DESCRIPTION AS UNIT_CLASS_DESC,
    f.PHASE,
    f.SECTION,
    f.BLOCK,
    f.LOT,
    f.UNITCOST,
    f.FINTYPECODE,
    ft.DESCRIPTION AS FIN_TYPE_DESC,
    f.RECUSER,
    f.RECDATE
FROM FACT_LOT_INVENTORY f
LEFT JOIN DIM_BRANCH b ON f.BRANCHID = b.BRANCHID
LEFT JOIN DIM_UNIT_TYPE ut ON f.UNITTYPE = ut.UNITTYPE
LEFT JOIN DIM_UNIT_CLASS uc ON f.UNITCLASS = uc.UNITCLASS
LEFT JOIN DIM_FINANCING_TYPE ft ON f.FINTYPECODE = ft.FINTYPECODE;
